name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "42 0 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:

      # ======================================================================================
      # üñºÔ∏è TEMPLATES
      # ======================================================================================

      # Classic template example
      - name: üìó Classic template
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # üß© PLUGINS
      # ======================================================================================

      # ======================================================================================
      # üèÜ Achievements

      # Achievements
      - name: üèÜ Achievements
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_only: polyglot, stargazer, developer, contributor, octonaut
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # üìÖ Isometric commit calendar

      # Display isometric calendar (365 days)
      - name: üìÖ Isocalendar plugin (full year)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # üà∑Ô∏è Most used languages

      # Display most used languages (with some unwanted languages ignored)
      - name: üà∑Ô∏è Languages plugin
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot
          plugin_languages_limit: 4
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # ======================================================================================
      # üßë‚Äçü§ù‚Äçüßë People plugin

      # Display followers
      - name: üßë‚Äçü§ù‚Äçüßë People plugin (followers)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: followers
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          output_action: pull-request
          delay: 120

      # Sponsors
      - name: üßë‚Äçü§ù‚Äçüßë People plugin (sponsors)
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@master
        with:
          filename: metrics.sponsors.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_types: sponsors
          plugin_people_size: 48
          plugins_errors_fatal: ${{ github.repository == 'lowlighter/lowlighter' }}
          config_display: large
          output_action: pull-request
          delay: 120
